build:
	@go build -o resolveIP main.go

run:
	@./resolveIP ip www.google.com
	@./resolveIP ip6 www.google.com
	@./resolveIP ip4:icmp www.google.com
	@./resolveIP ip4 www.yahoo.in
	@./resolveIP ip6 www.amazon.in
	@./resolveIP ip4 learner.pceterp.in